# -*- coding: utf-8 -*-
[core]
name = Agbirigba
hid = NOCODE_Agbirigba
level = language
macroareas = 
	Africa
countries = 
	NG
links = 
	https://www.wikidata.org/entity/Q28134318
	https://en.wikipedia.org/wiki/Agbirigba

[sources]
glottolog = 
	**hh:phon:AkinlabiNdimele:Agbirigba**

[classification]
sub = **hh:hv:Williamson:Niger-Delta**:80-82 **hh:hv:Manfredi:Igboid**
subrefs = 
	**hh:hv:Williamson:Niger-Delta**
	**hh:hv:Manfredi:Igboid**

