# -*- coding: utf-8 -*-
[core]
name = Arawan
level = family
links = 
	https://www.wikidata.org/entity/Q626772
	https://en.wikipedia.org/wiki/Arawan_languages

[classification]
sub = **hh:hv:Dienst:Arawan** **hh:hvld:Dienst:Arawan**
familyrefs = 
	**hh:hvld:Dienst:Arawan**
subrefs = 
	**hh:hvld:Dienst:Arawan**
	**hh:hv:Dienst:Arawan**

