# -*- coding: utf-8 -*-
[core]
name = Caspian and eastern Persia Gypsy
hid = NOCODE_Caspian-Eastern-Persia-Gypsy
level = language
macroareas = 
	Eurasia
countries = 
	IR

[sources]
glottolog = 
	**hh:w:Ivanow:Qainat**
	**hh:w:deMorgan:Nord-Perse**

[altnames]
hhbib_lgcode = 
	Djougi
	Gooudari
	Gowdari
	Qainat
	Qinat

[classification]
sub = **hh:h:Windfuhr:Iranian** **hh:hv:Korn:Central-Iranian** **hh:hv:Korn:Iranian-Isoglosses** **hh:hv:Cathcart:Iranian**:11-16
subrefs = 
	**hh:h:Windfuhr:Iranian**
	**hh:hv:Cathcart:Iranian**
	**hh:hv:Korn:Central-Iranian**
	**hh:hv:Korn:Iranian-Isoglosses**

