# -*- coding: utf-8 -*-
[core]
name = Northern Highland East Cushitic
level = family

[classification]
sub = **hh:hv:Hudson:HECushitic** **hh:hv:Sosal:Highland-East-Cushitic**
subrefs = 
	**hh:hv:Sosal:Highland-East-Cushitic**
	**hh:hv:Hudson:HECushitic**

[altnames]
glottolog = 
	Sidaama-Hadiyya-Kambaata

