# -*- coding: utf-8 -*-
[core]
name = Hadiyyaic
level = family

[classification]
sub = **hh:hv:Hudson:HECushitic** **hh:hv:Sosal:Highland-East-Cushitic**
subrefs = 
	**hh:hv:Sosal:Highland-East-Cushitic**
	**hh:hv:Hudson:HECushitic**

