# -*- coding: utf-8 -*-
[core]
name = Kankuamo
hid = NOCODE_Kankuamo
level = language
latitude = 10.750207
longitude = -73.357544
macroareas = 
	South America
countries = 
	CO
links = 
	https://en.wikipedia.org/wiki/Atanque_language
	https://www.wikidata.org/entity/Q3192697
timespan = 1932-01-01/1932-01-01

[sources]
glottolog = 
	**fabreall2009ann:Chibcha_kankuamo30**
	**hh:hv:Jackson:Chibchas-Sierra-Nevada**
	**hh:hv:Trillos:Chibchas-Sierra-Nevada**
	**hh:hvw:Constenla:Chibcha**
	**hh:hw:Lehmann:Zentral-Amerika:I**
	**hh:w:Celedon:Atanques**
	**hh:w:deWavrinTrillos:Kankuamo**

[triggers]
lgcode = 
	kankuamo
	formativo
	1501
	urbewohner
	matices
	taironaca
	coguis
	multiculturales
	atanques
	kogi
	kaggaba
	tropicale
	kagaba

[hh_ethnologue_comment]
comment = Kankuamo, an Eastern Arhuacic language (different from, but most closely related to Damana [mbp]), is missing
	(**hh:hv:Trillos:Chibchas-Sierra-Nevada**:70). See also: Malayo [mbp].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Kankuamo

[classification]
sub = **hh:hv:Constenla-Umana:Chibchan**
subrefs = 
	**hh:hv:Constenla-Umana:Chibchan**

[endangerment]
status = extinct
source = Glottolog
date = 2018-01-05T17:27:48
comment = Kankuamo (NOCODE_Kankuamo-NOCODE_Kankuamo) = 10 (Extinct).

[altnames]
hhbib_lgcode = 
	Atanques
	Atánquez

