# -*- coding: utf-8 -*-
[core]
name = Unclassified Purus
level = family

[classification]
sub = **hh:hv:deCarvalho:Purus** **hh:hv:daSilvaBrandao:Arawak** **hh:hvw:Ramirez:Arawak-Enciclopedia**:III:740-751
subrefs = 
	**hh:hvw:Ramirez:Arawak-Enciclopedia**
	**hh:hv:daSilvaBrandao:Arawak**
	**hh:hv:deCarvalho:Purus**

