# -*- coding: utf-8 -*-
[core]
name = Madi-Madiha
level = family

[classification]
sub = **hh:hv:Dienst:Arawan** **hh:hvld:Dienst:Arawan**
subrefs = 
	**hh:hvld:Dienst:Arawan**
	**hh:hv:Dienst:Arawan**

