# -*- coding: utf-8 -*-
[core]
name = Yelelihre
hid = NOCODE_Yelelihre
level = language
macroareas = 
	South America
countries = 
	BR

[sources]
glottolog = 
	**hh:h:Eberhard:Nambikwara**

[classification]
sub = **hh:g:Eberhard:Mamainde**:21-31
subrefs = 
	**hh:g:Eberhard:Mamainde**

