# -*- coding: utf-8 -*-
[core]
name = Nagramadu
level = language
hid = NOCODE_Nagramadu
countries = 
	ID
macroareas = 
	Papunesia
longitude = 134.77836
latitude = -3.33482
timespan = 1903-01-01/1903-01-01

[altnames]
hhbib_lgcode = 
	Nagramádu
	P 358 and 377 the village of Nagramuda on the upper Jago river

[classification]
sub = **hh:hv:UsherSuter:Asmat-Muli** **hh:hvw:Ray:ENetherlandsNG**
subrefs = 
	**hh:hv:UsherSuter:Asmat-Muli**
	**hh:hvw:Ray:ENetherlandsNG**

[endangerment]
status = extinct
source = Glottolog
date = 2026-07-28T16:27:00
comment = Nagramadu (NOCODE_Nagramadu-NOCODE_Nagramadu) = 10 (Extinct).

[hh_ethnologue_comment]
comment = The 1903 expedition to Lake Jamur of **hh:h:Wichmann:Geelvink-Jamur**:358, 377 encountered a village Nagramuda on the upper Jaho river in the Bird's Neck region of Papua, Indonesia. Some data was recorded of this language (under the name Nagramadu, **hh:ew:vanderSande:NNG**) and it is arguably related to Kamoro **hh:hvw:Ray:ENetherlandsNG** but far from close enough to count as the same language. No further information has been forthcoming and modern surveys suggest the area is Yeresiam [ire]-speaking so the language recorded in 1903 is presumably extinct. See also: Yerisiam [ire].
comment_type = Missing
ethnologue_versions = E16/E17/E18/E19/E20/E21/E22/E23/E24/E25/E26/E27/E28/E29
isohid = NOCODE_Nagramadu

[sources]
glottolog = 
	**hh:ew:vanderSande:NNG**
	**hh:h:Wichmann:Geelvink-Jamur**
	**hh:h:Wichmann:Neu-Guinea**
	**hh:hw:Galis:NNG**
	**hh:hw:Meyer:NNG**

