# -*- coding: utf-8 -*-
[core]
name = Sabakor-Nagramadu
level = family

[classification]
sub = **hh:hv:UsherSuter:Asmat-Muli** **hh:hvw:Ray:ENetherlandsNG**
subrefs = 
	**hh:hv:UsherSuter:Asmat-Muli**
	**hh:hvw:Ray:ENetherlandsNG**

